# Generated by Django 4.1.4 on 2022-12-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
